<?php

namespace App\Models;

use App\Database\CustomBuilder;
use App\Models\Enum\StatusNotif;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;



class NotifMobile extends Model
{
    use HasFactory;
    protected $table = 'notif_mobiles';
    protected $primaryKey = "id";
    protected $keyType = "string";
    protected $fillable = [
        'title',
        'message',
        'status',
        'karyawan_id',
        'category',
    ];

    protected $casts = [
        'status' => StatusNotif::class,
    ];

    public function newEloquentBuilder($query)
    {
        return new CustomBuilder($query); // TODO: Change the autogenerated stub
    }

    public function karyawan(){
        return $this->belongsTo(DataKaryawan::class,'karyawan_id','id');
    }
}
